### PR TITLE
Add validation inputs

### PR DESCRIPTION
**Pull request by Colecf**
These were added to regular ninja in:
https://github.com/ninja-build/ninja/commit/04c410b15b70fb321928ffba19d697db15cb0121

Android uses them, so they're needed to port android to n2. (which is something I'm exploring but not committing to)

### CODE REVIEW

**Comment by evmar** [comment]
Also, if for Android purposes you wanted to explore more invasive changes like a binary file format, I would be happy to explain any part of n2 you need.  But from this PR it feels like you already have pretty much gotten it.

**Comment by Colecf** [comment]
Thanks! I'm glad you're open to supporting android. Upstream backing is definitely a factor in the switch.

There's still a lot of work/investigation to port android to n2, but some other thoughts I had while looking into it:
  - Currently we hit the "used generated file, but has no dependency path to it" error, which is probably an issue in our ninja file
  - We rely on [a number of flags](https://cs.android.com/android/platform/superproject/main/+/main:build/soong/ui/build/ninja.go;l=54;drc=ded796030ba24c6ea096c26067890884825f9ebb) that are currently unsupported in n2, but maybe they're not all necessary. The frontend_file flag is pretty important though.
  - Our ninja fork does have multithreaded parsing. I haven't benchmarked the difference between it and n2 yet.
  - I'm not sure a binary format would be feasible for us, because all of our build system rules emit ninja code as mostly raw strings. So if there was a binary format, we'd have to either do a ton of work to rewrite all the rules or parse the text and convert it to binary.
  - I'm also investigating adding action sandboxing (probably with nsjail) and remote build (RBE) support to ninja. I was thinking maybe instead of shoehorning that into ninja/n2 (particuarly RBE), it might be better if n2 had some kind of plugin api to offload executing the actions to another program. And that program could do the RBE calls.
  - Some other minor features that our ninja fork has are an ETA based on prior runs, and the ability to tag build actions for later analysis.

**Comment by evmar** [comment]
Now that we're on the subject, didn't I see some rumor about Android switching to bazel?  Is that still happening?

**Comment by Colecf** [comment]
Unfortunately the migration to bazel was recently cancelled. :/

**Comment by evmar** [comment]
Is it worth opening bugs about the remaining issues?
Re the frontend_file, I had experimented a bit with https://github.com/evmar/n2/pull/34 which feels pretty similar

**Pull request merged**
